# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from algorithms import *
from draw import Draw
 

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimplify = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimplify.setObjectName("menuSimplify")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(parent=MainForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionMin_Bounding_Rectangle = QtGui.QAction(parent=MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/maer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionMin_Bounding_Rectangle.setIcon(icon1)
        self.actionMin_Bounding_Rectangle.setObjectName("actionMin_Bounding_Rectangle")
        self.actionPCAS = QtGui.QAction(parent=MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pca.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPCAS.setIcon(icon2)
        self.actionPCAS.setObjectName("actionPCAS")
        self.actionClear_results = QtGui.QAction(parent=MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/clear_ch.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon3)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/clear_er.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon4)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionLongest_Edge = QtGui.QAction(parent=MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/longestedge.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLongest_Edge.setIcon(icon5)
        self.actionLongest_Edge.setObjectName("actionLongest_Edge")
        self.actionWall_Average = QtGui.QAction(parent=MainForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/wa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWall_Average.setIcon(icon6)
        self.actionWall_Average.setObjectName("actionWall_Average")
        self.actionWeighted_bisector = QtGui.QAction(parent=MainForm)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/weightedbisector.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWeighted_bisector.setIcon(icon7)
        self.actionWeighted_bisector.setObjectName("actionWeighted_bisector")
        self.actionOpen = QtGui.QAction(parent=MainForm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon8)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSimplify.addAction(self.actionMin_Bounding_Rectangle)
        self.menuSimplify.addAction(self.actionPCAS)
        self.menuSimplify.addAction(self.actionLongest_Edge)
        self.menuSimplify.addAction(self.actionWall_Average)
        self.menuSimplify.addAction(self.actionWeighted_bisector)
        self.menuView.addAction(self.actionClear_results)
        self.menuView.addAction(self.actionClear_all)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimplify.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMin_Bounding_Rectangle)
        self.toolBar.addAction(self.actionPCAS)
        self.toolBar.addAction(self.actionLongest_Edge)
        self.toolBar.addAction(self.actionWall_Average)
        self.toolBar.addAction(self.actionWeighted_bisector)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        
        #Simplify building using MBR
        self.actionMin_Bounding_Rectangle.triggered.connect(self.simplifyBuildingMBRClick)
        self.actionClear_results.triggered.connect(self.clearResultsClick)
        self.actionPCAS.triggered.connect(self.simplifyBuildingPCAClick)
        self.actionOpen.triggered.connect(self.openClick)
        self.actionLongest_Edge.triggered.connect(self.simplifyBuildingLongestEdgeClick)
        self.actionWall_Average.triggered.connect(self.simplifyBuildingWallAverageClick)
        self.actionWeighted_bisector.triggered.connect(self.simplifyBuildingWeightedBisectorClick)
        self.actionClear_all.triggered.connect(self.clearAllClick) 
        self.actionExit.triggered.connect(MainForm.close)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        
        
    def simplifyBuildingPCAClick(self):
        a = Algorithms()
        
        #Process manually drawn building (if it exists)
        building = self.Canvas.getBuilding()
        if not building.isEmpty():
            mbr_res = a.simplifyBuildingPCA(building)
            self.Canvas.setMBR(mbr_res)
            
        #Process all loaded shapefile buildings
        loaded_buildings = self.Canvas.getBuildings()
        mbrs_res = []
        for b in loaded_buildings:
            if not b.isEmpty():
                mbrs_res.append(a.simplifyBuildingPCA(b))
                
        #Send the list of new MBRs back to the canvas
        self.Canvas.setMBRs(mbrs_res)
        self.Canvas.repaint()
        
    def simplifyBuildingMBRClick(self):
        a = Algorithms()
        
        #Process manually drawn building
        building = self.Canvas.getBuilding()
        if not building.isEmpty():
            mbr_res = a.simplifyBuildingMBR(building)
            self.Canvas.setMBR(mbr_res)
            
        #Process all loaded shapefile buildings
        loaded_buildings = self.Canvas.getBuildings()
        mbrs_res = []
        for b in loaded_buildings:
            if not b.isEmpty():
                mbrs_res.append(a.simplifyBuildingMBR(b))
                
        #Send the list of new MBRs back to the canvas
        self.Canvas.setMBRs(mbrs_res)
        self.Canvas.repaint()
        
    def simplifyBuildingLongestEdgeClick(self):
        a = Algorithms()
        
         #Process manually drawn building
        building = self.Canvas.getBuilding()
        if not building.isEmpty():
            mbr_res = a.simplifyBuildingLongestEdge(building)
            self.Canvas.setMBR(mbr_res)
            
        #Process all loaded shapefile buildings
        loaded_buildings = self.Canvas.getBuildings()
        mbrs_res = []
        for b in loaded_buildings:
            if not b.isEmpty():
                mbrs_res.append(a.simplifyBuildingLongestEdge(b))
                
        #Send the list of new MBRs back to the canvas
        self.Canvas.setMBRs(mbrs_res)
        self.Canvas.repaint()
        
    
    def simplifyBuildingWallAverageClick(self):
        a = Algorithms()
        
         #Process manually drawn building
        building = self.Canvas.getBuilding()
        if not building.isEmpty():
            mbr_res = a.simplifyBuildingWallAverage(building)
            self.Canvas.setMBR(mbr_res)
            
        #Process all loaded shapefile buildings
        loaded_buildings = self.Canvas.getBuildings()
        mbrs_res = []
        for b in loaded_buildings:
            if not b.isEmpty():
                mbrs_res.append(a.simplifyBuildingWallAverage(b))
                
        #Send the list of new MBRs back to the canvas
        self.Canvas.setMBRs(mbrs_res)
        self.Canvas.repaint()
        
    def simplifyBuildingWeightedBisectorClick(self):
        a = Algorithms()
        
         #Process manually drawn building
        building = self.Canvas.getBuilding()
        if not building.isEmpty():
            mbr_res = a.simplifyBuildingWeightedBisector(building)
            self.Canvas.setMBR(mbr_res)
            
        #Process all loaded shapefile buildings
        loaded_buildings = self.Canvas.getBuildings()
        mbrs_res = []
        for b in loaded_buildings:
            if not b.isEmpty():
                mbrs_res.append(a.simplifyBuildingWeightedBisector(b))
                
        #Send the list of new MBRs back to the canvas
        self.Canvas.setMBRs(mbrs_res)
        self.Canvas.repaint()   
            
        
    def clearResultsClick(self):
        #Clear results
        self.Canvas.clearResult()
        
    def openClick(self):
        self.Canvas.LoadShapesToScene()
    
    def clearAllClick(self):
        #Clear all data (buildings and results)
        self.Canvas.clearResult()
        self.Canvas.getBuildings().clear()
        self.Canvas.repaint()
    
        
        
    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Simplify buildings"))
        self.menuFile.setTitle(_translate("MainForm", "File"))
        self.menuSimplify.setTitle(_translate("MainForm", "Simplify"))
        self.menuView.setTitle(_translate("MainForm", "View"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionExit.setText(_translate("MainForm", "Exit"))
        self.actionExit.setToolTip(_translate("MainForm", "Close application"))
        self.actionMin_Bounding_Rectangle.setText(_translate("MainForm", "Min. Bounding Rectangle"))
        self.actionMin_Bounding_Rectangle.setToolTip(_translate("MainForm", "Simplify building using Minimum Bounding Rectangle"))
        self.actionPCAS.setText(_translate("MainForm", "PCA"))
        self.actionPCAS.setToolTip(_translate("MainForm", "Simplify building using PCA"))
        self.actionClear_results.setText(_translate("MainForm", "Clear results"))
        self.actionClear_all.setText(_translate("MainForm", "Clear all"))
        self.actionClear_all.setToolTip(_translate("MainForm", "Clear all data"))
        self.actionLongest_Edge.setText(_translate("MainForm", "Longest Edge"))
        self.actionLongest_Edge.setToolTip(_translate("MainForm", "Simplify building using Longest Edge"))
        self.actionWall_Average.setText(_translate("MainForm", "Wall Average"))
        self.actionWall_Average.setToolTip(_translate("MainForm", "Simplify building using Wall Average"))
        self.actionWeighted_bisector.setText(_translate("MainForm", "Weighted Bisector"))
        self.actionWeighted_bisector.setToolTip(_translate("MainForm", "Simplify building using Weighted Bisector"))
        self.actionOpen.setText(_translate("MainForm", "Open"))
        self.actionOpen.setToolTip(_translate("MainForm", "Open file"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec())
