# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from draw import Draw
from algorithms import * 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 1015)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(parent=self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuClear = QtWidgets.QMenu(parent=self.menubar)
        self.menuClear.setObjectName("menuClear")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_DT = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons/triangles2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreate_DT.setIcon(icon2)
        self.actionCreate_DT.setObjectName("actionCreate_DT")
        self.actionCreateContouLines = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons/contours2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreateContouLines.setIcon(icon3)
        self.actionCreateContouLines.setObjectName("actionCreateContouLines")
        self.actionAnalyzeSlope = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons/slope2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeSlope.setIcon(icon4)
        self.actionAnalyzeSlope.setObjectName("actionAnalyzeSlope")
        self.actionAnalyzeExposition = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons/orientation2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeExposition.setIcon(icon5)
        self.actionAnalyzeExposition.setObjectName("actionAnalyzeExposition")
        self.actionDT = QtGui.QAction(parent=MainWindow)
        self.actionDT.setCheckable(True)
        self.actionDT.setObjectName("actionDT")
        self.actionContour_lines_2 = QtGui.QAction(parent=MainWindow)
        self.actionContour_lines_2.setCheckable(True)
        self.actionContour_lines_2.setObjectName("actionContour_lines_2")
        self.actionSlope = QtGui.QAction(parent=MainWindow)
        self.actionSlope.setCheckable(True)
        self.actionSlope.setObjectName("actionSlope")
        self.actionExposition = QtGui.QAction(parent=MainWindow)
        self.actionExposition.setCheckable(True)
        self.actionExposition.setObjectName("actionExposition")
        self.actionClear_results = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon6)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/icons/clear_all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon7)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionParameters = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionParameters.setIcon(icon8)
        self.actionParameters.setObjectName("actionParameters")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAnalysis.addAction(self.actionCreate_DT)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionCreateContouLines)
        self.menuAnalysis.addAction(self.actionAnalyzeSlope)
        self.menuAnalysis.addAction(self.actionAnalyzeExposition)
        self.menuView.addAction(self.actionDT)
        self.menuView.addAction(self.actionContour_lines_2)
        self.menuView.addAction(self.actionSlope)
        self.menuView.addAction(self.actionExposition)
        self.menuClear.addAction(self.actionClear_results)
        self.menuClear.addSeparator()
        self.menuClear.addAction(self.actionClear_all)
        self.menuSettings.addAction(self.actionParameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_DT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreateContouLines)
        self.toolBar.addAction(self.actionAnalyzeSlope)
        self.toolBar.addAction(self.actionAnalyzeExposition)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionParameters)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        
        #Connects
        self.actionCreate_DT.triggered.connect(self.createDTClick)
        self.actionCreateContouLines.triggered.connect(self.createContourLinesClick)
        self.actionClear_results.triggered.connect(self.clearResultsClick)
        self.actionClear_all.triggered.connect(self.clearAllClick)
        self.actionOpen.triggered.connect(self.openFileClick)
        self.actionAnalyzeSlope.triggered.connect(self.analyzeSlopeClick)
        self.actionAnalyzeExposition.triggered.connect(self.analyzeExpositionClick)

        self.retranslateUi(MainWindow)
        
    def clearResultsClick(self):
        self.Canvas.clearResult()
        
    def clearAllClick(self):
        self.Canvas.clearAll()
    #User defined function
    def createDTClick(self):
        #Create DT
        
        #Get points
        points = self.Canvas.getPoints()
        
        #Create new object
        a = Algorithms()
        
        #Process data> create DT
        dt = a.createDT(points)
        
        #Set results
        self.Canvas.setDT(dt)
        
        #Repaint
        self.Canvas.repaint()
        
        
    def createContourLinesClick(self):
        #Create contour lines
        DT = self.Canvas.getDT()
        
        #We need to create DT
        if len(DT) <3:
            
            #Generate DT
            self.createDTClick()
            
            #Get DT
            DT = self.Canvas.getDT()
        
        #Get points from canvas for dynamic range calculation
        points = self.Canvas.getPoints()
        
        #Protect against empty data
        if not points:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "No data loaded for contour line calculation.")
            return

        #Dynamic calculation of z_min and z_max based on the loaded points, to provide user with relevant information for contour line step selection
        z_values = [p.z() for p in points]
        z_min = int(min(z_values))
        z_max = int(max(z_values))

        #Pop up dialog for user to input contour line step (dz), with dynamic information about the range of z values in the data. Consulted and partially developed with AI
        dz, ok = QtWidgets.QInputDialog.getInt(
            self.centralwidget, 
            "Contour Line Step", 
            f"Input contour line step (dz) in meters\n(Detected elevation range is {z_min} m to {z_max} m):", 
            10,    # Initial value in the field (e.g., 10 meters)
            1,     # Minimum allowed step value
            1000,  # Maximum allowed step value
            1      # Step size when clicking the arrows
        )

        #Canculation if everything is inputed correctly
        if ok and dz > 0:
            a = Algorithms()
            contours = a.createContourLines(DT, z_min, z_max, dz)

        #Set results
        self.Canvas.setContours(contours)
        
        #Repaint
        self.Canvas.repaint()
        
    def openFileClick(self):
        #Dialog for file selection (In part created with AI)
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Open Text File", "", "Text Files (*.txt);;All Files (*)")
        
        #Check if user selected a file
        if not file_path:
            return
            
        try:
            points = []
            with open(file_path, 'r', encoding='utf-8') as file:
                for line in file:
                    #Split line into coordinates and convert to float
                    coords = line.strip().split()
                    if len(coords) == 3:
                        x = float(coords[0])
                        y = float(coords[1])
                        z = float(coords[2])
                        points.append(QPoint3DF(x, y, z))
            
            if points:
                #Clear old data and set new data
                self.Canvas.clearAll()
                #Bounding box for data out of the screen resolution for afinne transformation (logic based on stack overflow: https://stackoverflow.com/questions/1752901/affine-transformation)
                min_x = min(p.x() for p in points)
                max_x = max(p.x() for p in points)
                min_y = min(p.y() for p in points)
                max_y = max(p.y() for p in points)
                
                dx = max_x - min_x
                dy = max_y - min_y
                
                #Set of canvas resolution with 50 point margin
                margin = 50
                canvas_w = self.Canvas.width() - 2 * margin
                canvas_h = self.Canvas.height() - 2 * margin
                
                #Scale calculation to fit data into canvas while maintaining aspect ratio
                scale = min(canvas_w / dx, canvas_h / dy) if dx > 0 and dy > 0 else 1.0
                
                #Calculation of the centroid of the canvas for centering the data
                center_x = min_x + dx / 2
                center_y = min_y + dy / 2
                canvas_center_x = self.Canvas.width() / 2
                canvas_center_y = self.Canvas.height() / 2
                
                #Transformation and adding points to canvas
                for p in points:
                    x_canvas = canvas_center_x + (p.x() - center_x) * scale
                    y_canvas = canvas_center_y - (p.y() - center_y) * scale
                    
                    #Z value is not transformed, only x and y for visualization, z is used for analysis
                    transformed_point = QPoint3DF(x_canvas, y_canvas, p.z())
                    self.Canvas.getPoints().append(transformed_point)
                    
                self.Canvas.repaint()
        except Exception as e:
            print(f"Error opening file: {e}")
            
    def analyzeSlopeClick(self):
        #Analyze slope
        DT = self.Canvas.getDT()
        
        #We need to create DT
        if len(DT) <3:
            #Generate DT
            self.createDTClick()
            #Get DT
            DT = self.Canvas.getDT()
        
        #Create TIN
        a = Algorithms()
        tin = a.createTIN(DT)
        slope_TIN = a.analyzeSlope(tin)
        
        #Set results with the "slope" tag
        self.Canvas.setTIN(slope_TIN, "slope")
        
        #Repaint
        self.Canvas.repaint()
        
    def analyzeExpositionClick(self):
        #Analyze exposition
        DT = self.Canvas.getDT()
        if len(DT) < 3:
            self.createDTClick()
            DT = self.Canvas.getDT()
            if len(DT) < 3:
                return

        a = Algorithms()
        tin = a.createTIN(DT)
        
        aspect_TIN = a.analyzeExposition(tin)
        
        #Passing resoults with the "aspect" tag
        self.Canvas.setTIN(aspect_TIN, "aspect")
        
        self.Canvas.repaint()
        
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTM Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open file"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Backspace"))
        self.actionCreate_DT.setText(_translate("MainWindow", "Create DT"))
        self.actionCreate_DT.setToolTip(_translate("MainWindow", "Create Delaunay triangulation"))
        self.actionCreateContouLines.setText(_translate("MainWindow", "Create contour lines"))
        self.actionAnalyzeSlope.setText(_translate("MainWindow", "Analyze slope"))
        self.actionAnalyzeSlope.setToolTip(_translate("MainWindow", "Analyze DTM slope"))
        self.actionAnalyzeExposition.setText(_translate("MainWindow", "Analyze exposition"))
        self.actionAnalyzeExposition.setToolTip(_translate("MainWindow", "Analyze DTM exposition"))
        self.actionDT.setText(_translate("MainWindow", "DT"))
        self.actionContour_lines_2.setText(_translate("MainWindow", "Contour lines"))
        self.actionSlope.setText(_translate("MainWindow", "Slope"))
        self.actionExposition.setText(_translate("MainWindow", "Exposition"))
        self.actionClear_results.setText(_translate("MainWindow", "Clear results"))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all"))
        self.actionParameters.setText(_translate("MainWindow", "Parameters"))
from draw import Draw

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
